---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-demo
  template:
    metadata:
      labels:
        app: api-demo
    spec:
      containers:
      - name: api-demo
        image: joelatngrok/api-demo:latest
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: api-demo-service
spec:
  selector:
    app: api-demo
  ports:
  - port: 4000
    targetPort: 4000
